dist: xenial
language: go
go:
- 1.11.x
- 1.12.x
env:
 - GO111MODULE=on
before_install:
  # Install Docker CLI
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" -y
  - sudo apt-get update -q
  - sudo apt-get install docker-ce-cli -y
  
  # podman doesn't currently ship with varlink interface
  # https://github.com/containers/libpod/issues/3027
  # Have to build it from scratch...
  # This is horrible and I'm sorry for everything :(
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update -q
  # ^- for libgpgme-dev
  - wget http://packages.linuxmint.com/pool/main/l/linuxmint-keyring/linuxmint-keyring_2016.05.26_all.deb
  - sudo dpkg -i linuxmint-keyring_2016.05.26_all.deb
  - sudo add-apt-repository "deb http://packages.linuxmint.com/ sylvia import" -y
  - sudo apt-get update -q
  # ^- for libostree-dev
  - >
    sudo apt-get install
    btrfs-tools
    git
    golang-go
    go-md2man
    iptables
    libassuan-dev
    libc6-dev
    libdevmapper-dev
    libglib2.0-dev
    libgpgme-dev
    libgpg-error-dev
    libostree-dev
    libprotobuf-dev
    libprotobuf-c0-dev
    libseccomp-dev
    libselinux1-dev
    libsystemd-dev
    pkg-config
    runc
    uidmap -y
  - git clone https://github.com/containers/libpod/ $GOPATH/src/github.com/containers/libpod
  - cd $GOPATH/src/github.com/containers/libpod
  - GO111MODULE=auto make BUILDTAGS="selinux seccomp varlink"
  - sudo make install PREFIX=
  # Ensure we're in the directory with our sources
  - cd $TRAVIS_BUILD_DIR
before_script:
  # Stop Docker daemon to ensure that we're hitting a proxy
  - sudo service docker stop
  # Create the systemd files
  - sudo echo "[Unit]" >> /usr/lib/systemd/system/io.podman.socket
  - sudo echo "Description=Pod Manager Socket" >> /usr/lib/systemd/system/io.podman.socket
  - sudo echo "[Socket]" >> /usr/lib/systemd/system/io.podman.socket
  - sudo echo "ListenStream=/run/podman/io.podman" >> /usr/lib/systemd/system/io.podman.socket
  - sudo echo "[Install]" >> /usr/lib/systemd/system/io.podman.socket
  - sudo echo "WantedBy=sockets.target" >> /usr/lib/systemd/system/io.podman.socket
  - sudo echo "[Unit]" >> /usr/lib/systemd/system/io.podman.service
  - sudo echo "Description=Pod Manager" >> /usr/lib/systemd/system/io.podman.service
  - sudo echo "Requires=io.podman.socket" >> /usr/lib/systemd/system/io.podman.service
  - sudo echo "After=io.podman.socket" >> /usr/lib/systemd/system/io.podman.service
  - sudo echo "[Service]" >> /usr/lib/systemd/system/io.podman.service
  - sudo echo "Type=simple" >> /usr/lib/systemd/system/io.podman.service
  - sudo echo "ExecStart=/usr/bin/podman --varlink=unix:/run/io.podman" >> /usr/lib/systemd/system/io.podman.service
  - sudo echo "[Install]" >> /usr/lib/systemd/system/io.podman.service
  - sudo echo "WantedBy=multi-user.target" >> /usr/lib/systemd/system/io.podman.service
  - sudo echo "Also=io.podman.socket" >> /usr/lib/systemd/system/io.podman.service
  # Start podman
  - sudo systemctl enable io.podman.socket
  - sudo systemctl start io.podman.socket
  - varlink call unix:/run/io.podman/io.podman.Ping
  - podman version
