dist: xenial
language: go
go:
  - 1.11.x
  - 1.12.x
before_install:
  # Install Docker CLI
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" -y
  - sudo apt-get update -q
  - sudo apt-get install docker-ce-cli -y
  - sudo mkdir -p /etc/containers
  - sudo curl https://raw.githubusercontent.com/containers/skopeo/master/default-policy.json -o /etc/containers/policy.json
  # Install podman runtime dependencies
  - sudo add-apt-repository ppa:projectatomic/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install podman -y

  # Ensure we're in the directory with our sources
  - cd $TRAVIS_BUILD_DIR
before_script:
  # Stop Docker daemon to ensure that we're hitting a proxy
  - sudo service docker stop
  - sudo rm -f /var/run/docker.sock
  # Create the systemd files
  - sudo cp $TRAVIS_BUILD_DIR/tests/io.docker.socket /usr/lib/systemd/system/io.docker.socket
  - sudo cp $TRAVIS_BUILD_DIR/tests/io.docker.service /usr/lib/systemd/system/io.docker.service
  # Start podman
  - sudo systemctl enable io.podman.socket
  - sudo systemctl start io.podman.socket
  # Start dipod
  - sudo systemctl enable io.docker.socket
  - sudo systemctl start io.docker.socket
script:
  # Build and install our software
  - go build github.com/EricHripko/dipod/cmd/dipod
  - sudo cp dipod /usr/bin/dipod
  - sudo systemctl status io.podman.socket
  - sudo systemctl status io.docker.socket
  # Run tests
  - sudo bats tests/cli
